BOOK_DATABASE.push(
    { title: "Pend. Agama Islam 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Islam-BS-KLS-X.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Islam-BS-KLS-X-Cover.png", mapel: "Pend. Agama Islam" },
    { title: "Bahasa Indonesia 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa_Indonesia_BS_KLS_X_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Bahasa_Indonesia_BS_KLS_X_Rev_Cover.png", mapel: "Bahasa Indonesia" },
    { title: "Bahasa Inggris 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Bahasa-Inggris-BS-KLS-X.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Bahasa-Inggris-BS-KLS-X-cover.png", mapel: "Bahasa Inggris" },
    { title: "Matematika 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika_BS_KLS_X_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Matematika_BS_KLS_X_Rev_Cover.png", mapel: "Matematika" },
    { title: "IPA 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPA_BS_KLS_X_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/IPA_BS_KLS_X_Rev_Cover.png", mapel: "IPA" },
    { title: "Koding & KA 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/KKA_BS_KLS_10.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/KKA_BS_KLS_10_Cover.PNG", mapel: "Koding & KA" },
    { title: "IPS 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/IPS_BS_KLS_X_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/IPS_BS_KLS_X_Rev_Cover.png", mapel: "IPS" },
    { title: "Sejarah 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Sejarah-BS-KLS-X.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Sejarah-BS-KLS-X-Cover.png", mapel: "Sejarah" },
    { title: "Informatika 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Informatika_BS_KLS_X_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Informatika_BS_KLS_X_Rev_Cover.PNG", mapel: "Informatika" },
    { title: "PJOK 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/PJOK_BS_KLS_X.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/PJOK_BS_KLS_X_Cover.png", mapel: "PJOK" },
    { title: "PKN 10", jenjang: "SMA", kelas : "10", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-X.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Pendidikan-Pancasila-BS-KLS-X-Cover.png", mapel: "PKN" },
    { title: "Matematika 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Matematika_BS_XII_TL_Rev.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Matematika_BS_XII_TL_Rev_Cover.PNG", mapel: "Matematika" },
    { title: "Bahasa Indonesia 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Indonesia_BS_KLS_XII_Rev_.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Indonesia_BS_KLS_XII_Rev_Cover.PNG", mapel: "Bahasa Indonesia" },
    { title: "Bahasa Korea 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Korea_BS_KLS_XII_.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Korea_BS_KLS_XII_Cover.PNG", mapel: "Bahasa Korea" },
    { title: "Pend. Pancasila 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Pendidikan-Pancasila-BS-KLS-XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Pendidikan-Pancasila-BS-KLS-XII-Cover.png", mapel: "Pend. Pancasila" },
    { title: "Pend. Agama Kristen 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Kristen-BS-KLS-XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Kristen-BS-KLS-XII-Cover.png", mapel: "Pend. Agama Kristen" },
    { title: "Pend. Agama Hindu 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Hindu-BS-KLS-XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Hindu-BS-KLS-XII-Cover.png", mapel: "Pend. Agama Hindu" },
    { title: "Pend. Agama Buddha 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Buddha_BS_KLS_XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Buddha_BS_KLS_XII_Cover.png", mapel: "Pend. Agama Buddha" },
    { title: "Pend. Agama Katolik 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Katolik_BS_KLS_XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Katolik_BS_KLS_XII_Cover.png", mapel: "Pend. Agama Katolik" },
    { title: "Pend. Agama Khonghucu 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Khonghucu_BS_KLS_XII.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Khonghucu_BS_KLS_XII_Cover.png", mapel: "Pend. Agama Khonghucu" },
    { title: "Pend. Agama Islam 12", jenjang: "SMA", kelas : "12", url: "https://static-sc.cloudapp.web.id/content/pdf/bukuteks/kurikulum21/Islam_BS_KLS_XII_.pdf", cover : "https://static-sc.cloudapp.web.id/content/image/coverteks/coverkurikulum21/Islam_BS_KLS_XII_Cover.png", mapel: "Pend. Agama Islam" }

);